### PR TITLE
Use uniform visibility handler when specify no predefined visibility

### PR DESCRIPTION
**Pull request by rwinzhang**
Depends on https://github.com/thephpleague/flysystem/pull/1629

Note: need to update composer.json file after above PR merged

### CODE REVIEW

**Comment by freekmurze** [comment]
> Note: need to update composer.json file after above PR merged

Could you already make the needed changes in this PR?

**Comment by rwinzhang** [comment]
I haven't. I will update it after this PR https://github.com/thephpleague/flysystem/pull/1629 is merged

**Comment by AlexVanderbist** [comment]
Hey there, the default `PortableVisibilityHandler` that we're currently using also supports the `NO_PREDEFINED_VISIBILITY` option (https://github.com/thephpleague/flysystem-google-cloud-storage/blob/3.x/PortableVisibilityHandler.php#L55). It should be enough to add the `NO_PREDEFINED_VISIBILITY` option to the array of accepted visibility options in this package to get this to work. I'll send a separate PR.

**Comment by rwinzhang** [comment]
It also need to pass UniformBucketLevelAccessVisibility too. I also add getClient public method like the s3 driver

**Comment by AlexVanderbist** [comment]
I think the default `PortableVisibilityHandler` already provides a way to avoid the error when `visibility = NO_PREDEFINED_VISIBILITY`. I'll merge this PR but make some changes to keep the default visibility handler. I'll also make sure that the visibility handler is configurable for when https://github.com/thephpleague/flysystem/pull/1629 eventually gets merged.

Thanks for the PR!

**Pull request merged**
